package com.complover116.timezone;

public enum GameState {
	TIME_GOES,
	ATTACKERS_CONTROL,
	DEFENDERS_CONTROL,
	BUILD_MODE,
	CONSTRUCT_MODE,
	FAST_FORWARD,
	LOADING_SCREEN,
	TERRITORY_LOADING,
	TERRITORY_LOAD_DELAY,
	ERROR
}
